OBJECTS = spike_io_sender.o \
          sender_interface_forward.o \
          sender_interface_backward.o

OBJS=$(OBJECTS:%=build/%)

all: sender

build/%.o: %.cpp
	-mkdir -p $(dir $@)
	g++ -g -o $@ -c $<

sender: $(OBJS)
	g++ -L../.. -o $@ $^  -lspynnaker_external_device_lib -lGL -lGLU -lglut -lpthread -lsqlite3

clean:
	rm -rf build
