OBJECTS = spike_io_receiver.o \
          receiver_interface.o

OBJS=$(OBJECTS:%=build/%)

all: receiver

build/%.o: %.cpp
	-mkdir -p $(dir $@)
	g++ -o $@ -c $<

receiver: $(OBJS)
	g++ -L.. -o $@ $^  -lspynnaker_external_device_lib -lGL -lGLU -lglut -lpthread -lsqlite3

clean:
	rm -rf build
