OBJECTS = spike_io_sender_receiver.o \
          sender_interface_forward.o \
          sender_interface_backward.o \
          receiver_interface.o

APP = sender_receiver

include ../../Makefile.app
