OBJECTS = UDPConnection.o \
          SpynnakerDatabaseConnection.o \
          DatabaseReader.o \
          SpynnakerLiveSpikesConnection.o \
          EIEIOMessage.o \
          ConnectionListener.o
   
OBJS=$(OBJECTS:%=build/%)

all: libspynnaker_external_device_lib.a

build/%.o: %.cpp
	-mkdir -p $(dir $@)
	g++ -g -o $@ -c $<

libspynnaker_external_device_lib.a: $(OBJS)
	$(RM) $@
	$(AR) rcs $@ $(OBJS)

clean:
	rm -rf build
