OBJECTS = spike_io_sender.o \
          sender_interface_forward.o \
          sender_interface_backward.o \
          receiver_interface.o

OBJS=$(OBJECTS:%=build/%)

all: $(OBJS)

build/%.o: %.cpp
	-mkdir -p $(dir $@)
	g++ -L../.. -D FREEGLUT_STATIC -D WINVER=0x501 -D WIN32_LEAN_AND_MEAN -fpermissive -o $@ -c $<

clean:
	rm -rf build
