OBJECTS = spike_io_sender_receiver.o \
          sender_interface_forward.o \
          sender_interface_backward.o \
          receiver_interface.o

OBJS=$(OBJECTS:%=build/%)

all: sender_receiver

build/%.o: %.cpp
	-mkdir -p $(dir $@)
	g++ -g -o $@ -c $<

sender_receiver: $(OBJS)
	g++ -L../.. -o $@ $^  -lspynnaker_external_device_lib -lGL -lGLU -lglut -lpthread -lsqlite3

clean:
	rm -rf build
